
export const DID_FETCH_COMMUNITY = 'DID_FETCH_COMMUNITY'; // 已获取社区话题

export const DID_START_COMMIT_COMMENT = 'DID_START_COMMIT_COMMENT'; // 开始提交评论

export const DID_FINISH_COMMIT_COMMENT = 'DID_FINISH_COMMIT_COMMENT'; // 成功提交评论