"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
}
Object.defineProperty(exports, "__esModule", { value: true });
const team_detail_dal_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_dal"));
const team_detail_den_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_den"));
const team_detail_gsw_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_gsw"));
const team_detail_hou_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_hou"));
const team_detail_lac_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_lac"));
const team_detail_lal_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_lal"));
const team_detail_mem_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_mem"));
const team_detail_min_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_min"));
const team_detail_nop_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_nop"));
const team_detail_okc_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_okc"));
const team_detail_phx_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_phx"));
const team_detail_por_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_por"));
const team_detail_sac_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_sac"));
const team_detail_sas_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_sas"));
const team_detail_uta_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailWestern/team_detail_uta"));
const team_detail_atl_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_atl"));
const team_detail_bkn_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_bkn"));
const team_detail_bos_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_bos"));
const team_detail_cha_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_cha"));
const team_detail_chi_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_chi"));
const team_detail_cle_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_cle"));
const team_detail_det_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_det"));
const team_detail_ind_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_ind"));
const team_detail_mia_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_mia"));
const team_detail_mil_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_mil"));
const team_detail_nyk_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_nyk"));
const team_detail_orl_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_orl"));
const team_detail_phi_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_phi"));
const team_detail_tor_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_tor"));
const team_detail_was_1 = __importDefault(require("../mock_datas/teamDetail/teamDetailEastern/team_detail_was"));
const team_basic_dal_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_dal"));
const team_basic_den_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_den"));
const team_basic_gsw_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_gsw"));
const team_basic_hou_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_hou"));
const team_basic_lac_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_lac"));
const team_basic_lal_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_lal"));
const team_basic_mem_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_mem"));
const team_basic_min_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_min"));
const team_basic_nop_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_nop"));
const team_basic_okc_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_okc"));
const team_basic_phx_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_phx"));
const team_basic_por_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_por"));
const team_basic_sac_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_sac"));
const team_basic_sas_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_sas"));
const team_basic_uta_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicWestern/team_basic_uta"));
const team_basic_atl_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_atl"));
const team_basic_bkn_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_bkn"));
const team_basic_bos_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_bos"));
const team_basic_cha_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_cha"));
const team_basic_chi_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_chi"));
const team_basic_cle_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_cle"));
const team_basic_det_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_det"));
const team_basic_ind_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_ind"));
const team_basic_mia_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_mia"));
const team_basic_mil_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_mil"));
const team_basic_nyk_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_nyk"));
const team_basic_orl_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_orl"));
const team_basic_phi_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_phi"));
const team_basic_tor_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_tor"));
const team_basic_was_1 = __importDefault(require("../mock_datas/teamBasic/teamBasicEastern/team_basic_was"));
function mapTeamIdToDetail(id) {
    switch (id) {
        case '1610612745': return team_detail_hou_1.default;
        case '1610612744': return team_detail_gsw_1.default;
        case '1610612757': return team_detail_por_1.default;
        case '1610612760': return team_detail_okc_1.default;
        case '1610612762': return team_detail_uta_1.default;
        case '1610612740': return team_detail_nop_1.default;
        case '1610612759': return team_detail_sas_1.default;
        case '1610612750': return team_detail_min_1.default;
        case '1610612743': return team_detail_den_1.default;
        case '1610612746': return team_detail_lac_1.default;
        case '1610612747': return team_detail_lal_1.default;
        case '1610612758': return team_detail_sac_1.default;
        case '1610612742': return team_detail_dal_1.default;
        case '1610612763': return team_detail_mem_1.default;
        case '1610612756': return team_detail_phx_1.default;
        case '1610612761': return team_detail_tor_1.default;
        case '1610612738': return team_detail_bos_1.default;
        case '1610612755': return team_detail_phi_1.default;
        case '1610612739': return team_detail_cle_1.default;
        case '1610612754': return team_detail_ind_1.default;
        case '1610612748': return team_detail_mia_1.default;
        case '1610612749': return team_detail_mil_1.default;
        case '1610612764': return team_detail_was_1.default;
        case '1610612765': return team_detail_det_1.default;
        case '1610612766': return team_detail_cha_1.default;
        case '1610612752': return team_detail_nyk_1.default;
        case '1610612751': return team_detail_bkn_1.default;
        case '1610612741': return team_detail_chi_1.default;
        case '1610612753': return team_detail_orl_1.default;
        case '1610612737': return team_detail_atl_1.default;
        default: return '';
    }
}
exports.mapTeamIdToDetail = mapTeamIdToDetail;
function mapTeamIdToBasic(id) {
    switch (id) {
        case '1610612745': return team_basic_hou_1.default;
        case '1610612744': return team_basic_gsw_1.default;
        case '1610612757': return team_basic_por_1.default;
        case '1610612760': return team_basic_okc_1.default;
        case '1610612762': return team_basic_uta_1.default;
        case '1610612740': return team_basic_nop_1.default;
        case '1610612759': return team_basic_sas_1.default;
        case '1610612750': return team_basic_min_1.default;
        case '1610612743': return team_basic_den_1.default;
        case '1610612746': return team_basic_lac_1.default;
        case '1610612747': return team_basic_lal_1.default;
        case '1610612758': return team_basic_sac_1.default;
        case '1610612742': return team_basic_dal_1.default;
        case '1610612763': return team_basic_mem_1.default;
        case '1610612756': return team_basic_phx_1.default;
        case '1610612761': return team_basic_tor_1.default;
        case '1610612738': return team_basic_bos_1.default;
        case '1610612755': return team_basic_phi_1.default;
        case '1610612739': return team_basic_cle_1.default;
        case '1610612754': return team_basic_ind_1.default;
        case '1610612748': return team_basic_mia_1.default;
        case '1610612749': return team_basic_mil_1.default;
        case '1610612764': return team_basic_was_1.default;
        case '1610612765': return team_basic_det_1.default;
        case '1610612766': return team_basic_cha_1.default;
        case '1610612752': return team_basic_nyk_1.default;
        case '1610612751': return team_basic_bkn_1.default;
        case '1610612741': return team_basic_chi_1.default;
        case '1610612753': return team_basic_orl_1.default;
        case '1610612737': return team_basic_atl_1.default;
        default: return '';
    }
}
exports.mapTeamIdToBasic = mapTeamIdToBasic;
//# sourceMappingURL=mapTeamJson.js.map